{
 "title": "DoS/DDoS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mo",
    "query": "select left(tablename, length(tablename) - length('ingress_total') - 1) from pg_catalog.pg_tables where tablename like '%ingress_total'"
   },
   {
    "name": "type",
    "query": "select name as __value, description as __text from attacks"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "select xtime as time, pps, bps from\n( SELECT\n   distinct to_timestamp( round( extract('epoch' from time) / 60) * 60) as xtime,\n   sum(packets)/60 as pps,\n   sum(octets)/60 * 8 as bps\n FROM \"${mo}-ingress${type}_total\"\n WHERE\n  $__timeFilter(time)\n GROUP BY xtime\n) as r\nORDER BY time"
    }
   ]
  },
  {
   "title": "IP dst",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as ip, name from xe_rep('\"${mo}-ingress${type}_daddr\"', 'dst_host', 'packets', '/15', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  },
  {
   "title": "Source port",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as port, name from xe_rep('\"${mo}-ingress${type}_sport\"', 'src_port', 'packets', '/15', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  },
  {
   "title": "Destination port",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as port, name from xe_rep('\"${mo}-ingress${type}_dport\"', 'dst_port', 'packets', '/30', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  },
  {
   "title": "Average PPS per IP",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "select\n  dst_host::text as ip,\n  sum(packets) / ($__unixEpochTo() - $__unixEpochFrom()) * 1 as pps\nfrom \"${mo}-ingress${type}_daddr\"\nwhere\n  $__timeFilter(time)\n  and dst_host is not null\ngroup by dst_host\norder by pps desc\nlimit 40"
    }
   ]
  },
  {
   "title": "95th percentile",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "select ip, pt/15 * 1.0 as pps from\n(\n  select\n    dst_host::text as ip,\n    percentile_cont(0.95) within group (order by packets) as pt\n  from \"${mo}-ingress${type}_daddr\"\n  where\n      $__timeFilter(time)  \n    and dst_host is not null\n  group by ip\n) as report\norder by pps desc\nlimit 40"
    }
   ]
  }
 ]
}