{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mo",
    "query": "select left(tablename, length(tablename) - length('ingress_total') - 1) from pg_catalog.pg_tables where tablename like '%ingress_total'"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "select coalesce(etime, itime) as time, coalesce(ingress_bps, 0) as ingress_bps, coalesce(-egress_bps, 0) as egress_bps from\n(\n  (select to_timestamp( round( extract('epoch' from \"${mo}-egress_total\".time) / 60) * 60) as etime, sum(octets) / 60 * 8 as egress_bps from \"${mo}-egress_total\" where $__timeFilter(time) group by etime) as a\n  FULL OUTER JOIN\n  (select to_timestamp( round( extract('epoch' from \"${mo}-ingress_total\".time) / 60) * 60) as itime, sum(octets) / 60 * 8 as ingress_bps from \"${mo}-ingress_total\" where $__timeFilter(time) group by itime) as b\n    on a.etime = b.itime\n)\n  as x\n  order by time"
    }
   ]
  },
  {
   "title": "IP protocols",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "select time, ingress, egress, iana_protocols.name as proto from\n(\n  select coalesce(etime, itime) as time, coalesce(io, 0) as ingress, coalesce(-eo, 0) as egress, coalesce(eproto, iproto) as nproto from\n  (\n    (select to_timestamp( round( extract('epoch' from time) / 60 ) * 60) as etime, sum(octets)/60 * 8 AS eo, proto as eproto FROM \"${mo}-egress_proto\" WHERE $__timeFilter(time) GROUP BY etime, proto) as a\n    FULL OUTER JOIN\n    (select to_timestamp( round( extract('epoch' from time) / 60 ) * 60) as itime, sum(octets)/60 * 8 AS io, proto as iproto FROM \"${mo}-ingress_proto\" WHERE $__timeFilter(time) GROUP BY itime, proto) as b\n    on a.etime = b.itime and a.eproto=b.iproto\n  ) as x\n) as y\nJOIN iana_protocols on y.nproto=iana_protocols.num\norder by time"
    }
   ]
  },
  {
   "title": "IP dst ingress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as ip, name from xe_rep('\"${mo}-ingress_daddr\"', 'dst_host', 'octets', '/15*8', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  },
  {
   "title": "IP src ingress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as ip, name from xe_rep('\"${mo}-ingress_saddr\"', 'src_host', 'octets', '/15*8', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  },
  {
   "title": "IP src egress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as ip, name from xe_rep('\"${mo}-egress_saddr\"', 'src_host', 'octets', '/15*8', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  },
  {
   "title": "IP dst egress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "select tm as time, val as ip, name from xe_rep('\"${mo}-egress_daddr\"', 'dst_host', 'octets', '/15*8', $$ $__timeFilter(time) $$, 20);"
    }
   ]
  }
 ]
}